spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shayFoo/config-repo
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  lifecycle:
    timeout-per-shutdown-phase: 15s
server:
  port: 8888
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

