spring:
  application:
    name: config-service

  config:
    additional-location: "classpath:/local/application-local.yaml"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shayFoo/config-repo
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

