spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shayFoo/config-repo
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  lifecycle:
    timeout-per-shutdown-phase: 15s
management:
    endpoints:
      web:
        exposure:
          include: health,prometheus
    endpoint:
      health:
        show-details: always
        show-components: always
        probes:
          enabled: true
    metrics:
      tags:
        application: ${spring.application.name}
    tracing:
      sampling:
        probability: 1.0
    otlp:
      tracing:
        endpoint: http://localhost:4318/v1/traces
        compression: none
        timeout: 10s
server:
  port: 8888
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

